import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@stream-io/video-react-sdk/dist/css/styles.css"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import ConvexClerkProvider from "@/components/provider/ConvexClerkProvider"
import Navbar from "@/components/Navbar"
import { ThemeProvider } from "@/components/provider/ThemeProvider"
import { SignedIn, SignedOut, RedirectToSignIn } from "@clerk/nextjs"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="system" 
            enableSystem 
            disableTransitionOnChange>
            
            <SignedIn>
              <div className="min-h-screen">
                <Navbar />
                  <main className="px-4 sm:px-6 lg:px-8">
                    {children}
                  </main>
              </div>
            </SignedIn>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
          </ThemeProvider>
          <Toaster />
        </body>
    </html>
    </ConvexClerkProvider>
  );
}
